### ISSUE TITLE
Tables B and D should be documented as optional

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-mobilities#11]
As far as I know, most partners don't implement the "recognition part" of the new EUC LA template. There is a place for this data in the XSD, but many partners won't be able to provide it. We should warn the client implementers about this, and make sure that server implementers know that this part is not required (but still recommended).

**Comment by wrygiel** [comment]
We could even think of taking it one step further and removing the "recognition part" from EWP.

As far as I know, the receiving HEI doesn't care about the exact contents of tables B and D. It does sign the LA, but it verifies only tables A and C. So, perhaps, we don't need to actually even suggest the exchange of this data? @erasmus-without-paper/all-members

**Comment by georgschermann** [comment]
We would be among those not using it in the near future, but we are good with both ways.

**Comment by wrygiel** [comment]
> Where are these tables defined?

In the EUC LA template (attached in the repo).
