### ISSUE TITLE
Should we require nominee EQF level to be provided before nomination?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-mobilities#13]
Currently, `<nominee-eqf-level>` is [required](https://github.com/erasmus-without-paper/ewp-specs-api-mobilities/blob/v0.2.1/endpoints/get-response.xsd#L313), but I'm not sure if this is correct.

* Will all sending partners be able to provide this information?
* Is it very important for the receiving partner?

I think we should make it recommended, but not required.

**Comment by wrygiel** [comment]
@kaiqu, what do you think.

**Comment by kaiqu** [comment]
It should probably be optional for Staff Mobilities. As for Student Mobilities, I leave it to people who know the domain better than I do.

**Comment by wrygiel** [comment]
This API supports "Student Mobility for Studies" only. Other types of mobilities are referenced in IIAs API, but not here.

**Comment by kaiqu** [comment]
> This API supports "Student Mobility for Studies" only.

In that case, I leave it to the domain experts - they presumably know if student mobilities can be meaningful without an EQF Level.

**Comment by NicoVanMoortel** [comment]
In which situation would a sending institution not be able to provide the EQF-level of it's student? For UGent it's ok to be mandatory.

**Comment by wrygiel** [comment]
> In which situation would a sending institution not be able to provide the EQF-level of it's student? For UGent it's ok to be mandatory.

@kamil-olszewski-uw, could you comment?

BTW, related issue: https://github.com/erasmus-without-paper/ewp-specs-api-mobilities/issues/20

Now, both of these new elements are optional. Should we make the second one (`<efq-level-studied-at-departure>`) required? Perhaps it's a bit safer to leave it optional after the splitting? Perhaps some HEIs might have problems with providing it?

**Comment by kamil-olszewski-uw** [comment]
Our IRO says that EQF level is usually not mandatory, but some receiving HEIs require it (e.g. they have different campuses for every level of studies). In those cases EQF level of studies at the moment of mobility is more important than EQF level of studies at the moment of nomination.

**Comment by wrygiel** [comment]
Both new elements were made optional in version 0.7.0.
