### ISSUE TITLE
Should we add reason codes?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-mobilities#15]
EUC LA template defines a set of "reasons for exceptional changes to study programme abroad".

![image](https://cloud.githubusercontent.com/assets/2168535/23467804/4c92d92a-fe9f-11e6-90d4-ea42d32fa5a2.png)

These reasons are used in table A2, but not B2:

![image](https://cloud.githubusercontent.com/assets/2168535/23467887/8423a84c-fe9f-11e6-8eeb-f3e3283e2487.png)

In our current (v0.3.0) Outgoing Mobility object we allow for reasons to be supplied in both A2 and B2 tables, but these reasons are optional, and they are text-only:

```xml
<xs:element name="reason" minOccurs="0" maxOccurs="1">
    <xs:annotation>
        <xs:documentation>
            An optional reason for the change.

            UI designers are advised to supply a number of suggested reasons for their
            users (so that they can pick one when making the change). You can start with
            those listed in the EUC LA PDF template. Users SHOULD be allowed to specify
            their own custom reason for the change too.

            Note, that we do not make use of the "reason numbers" suggested by the EUC LA
            PDF template. We also do not attempt to introduce any other identifiable IDs or
            codes at this time (but we may try to do so in future versions of this schema).
        </xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:sequence>
            <xs:element name="display-text" type="ewp:MultilineString" minOccurs="1" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        A human-readable description of the reason - preferrably in English. It will
                        often be printed in PDF LA document (e.g. in the "Reason for change" column of
                        A2 or B2 table - see attached EUC LA template).
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
```

My questions are:

* Do any of you believe that we SHOULD introduce codes for these reasons?
* If we should, then is it okay with you if we design these codes ourselves?

EUC seems to be using numbers 1-7 in its template, but - personally - I don't believe these numbers were "designed to last". I am rather sure that they will be changed in the next EUC LA PDF template. If we need reason codes (and I'm not sure if we do), then it seems safer to introduce our own set of codes.

@erasmus-without-paper/all-members

**Comment by NicoVanMoortel** [comment]
For UGent a code can be useful. 
If UGent is the sending HEI (and thus the master) we will have no problems providing a code and a 'text'
If UGent is the receiving HEI we can use the code if we can match it with our internal codes and fall back on the 'text' if not. 

If the code is introduced, an 'EWP set of codes' would help in coping with changes in the EUC LA PDF template

**Comment by wrygiel** [comment]
Please review commit https://github.com/erasmus-without-paper/ewp-specs-api-mobilities/commit/38a9fb3a531bab42a2c981b656ba94c41f306079 - I think it suits our needs.
