### ISSUE TITLE
A photo of a student?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-mobilities#18]
In one of the meetings someone suggested (I think it was @geirmv?) that perhaps a student photo might be included in our mobilities.

It's easy to add such field to the specification, but I would like to consult partners first.

* Would you like to use this photo in your client (for incoming students)? Would you import it into your system?
* Would you supply a photo yourself (for your outgoing students)?
* Are there any privacy issues to consider?

@erasmus-without-paper/all-members

**Comment by georgschermann** [comment]
yes yes no
for privacy concerns the photo is equivalent to every other personal data (at least in Austria)

**Comment by wrygiel** [comment]
Okay then, I'm going to introduce this now.

**Comment by pargentieri** [comment]
> valent to every other personal data (at least in Austria)

Ok and in the other countries?

but why this idea? why add the link to a photo?

**Comment by fioravanti-unibo** [comment]
> Okay then, I'm going to introduce this now.

Is this a joke? Please tell me this is a joke.
What you are suggesting is completely illegal in every European country, it is against the GDPR.
