### ISSUE TITLE
How to detect which institution's mobilities to send if there is no receiving_hei_id parameter provider?

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/ewp-specs-api-mobilities#40]
Hello,
In the readme docs (reference link below), the receiving hei id parameter is said to be optional. 

If this parameter is not sent to the responding client, how should the responding client select and include the mobilities of the receiving hei as it does not know which institution is the request made by?

REF: https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/stable-v1/endpoints/index.md#receiving_hei_id-repeatable-optional

Anything we are missing? Or if not, any solution or implementation suggestion?

Thanks,

**Comment by kamil-olszewski-uw** [comment]
For each index endpoint, if no parameter is given, all objects that can be accessed by the requester from all HEIs supported by the server node should be returned.

**Comment by sascoms** [comment]
So, how do you detect which are these HEIs that are covered by the requester node?

What is the suggested way or what is the common implementation to find out which HEIs?

As, there is only referrer URL and head/signature data sent/coming to the index endpoint?

**Comment by wrygiel** [comment]
Take a look at `getHeisCoveredBy*` methods here:

https://javadoc.io/doc/eu.erasmuswithoutpaper/ewp-registry-client/latest/eu/erasmuswithoutpaper/registryclient/RegistryClient.html

**Comment by kamil-olszewski-uw** [comment]
**EDIT:** I removed my last comment because it could be misleading to some extent (my knowledge was out of date). A more technical colleague will write here on this topic.

**Comment by sascoms** [comment]
Thank you all for your replies and the information

We have implemented a similar approach, detecting the heis covered by the signature data in the request headers.

Although, I am not comfortable about sending mobilities of all of -say- a 100 HEIs covered in the request (why sending all instititions' data?), there is no other way unless the receiving/requesting HEI id is made mandatory in the API.

Hope to see sending and receiving HEI ID parameters as mandatory in all APIs.
