### ISSUE TITLE
Type of mobility and virtual component planned dates

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-mobilities#43]
Wouldn't it make sense for the version 2 of this API to include information about whether the mobility is semestral/short-term-doctoral/blended and the planned start/end dates of the virtual part (if applicable)?

**Comment by janinamincer-daszkiewicz** [comment]
Should these fields be mandatory?

**Comment by jiripetrzelka** [comment]
I think that the type of the mobility should be mandatory but the dates of the virtual part should be optional.

**Comment by kamil-olszewski-uw** [comment]
We definitely need to think about such fields, and we have been considering it for several months. But I guess it's too early for that. We don't have any specifications or official guidelines at the moment to rely on. The only source is the Beneficiary Module, which is very unstable at the moment (we are aware of its possible business errors), so I wouldn't consider any of the items in BM as final.

I'm not sure if the three types of LA will clearly translate into types of mobility. For example, there are long-term blended mobilities that were already set to decline after the pandemic, but are still there. Regarding short-term mobility, there are BIPs (Blended Intensive Programmes), but according to my IRO, there are also other short-term ones. Intuitively, BIPs for sure correspond to blended LAs, but according to our National Agency, there is no official confirmation of this. In general, our NA has not yet provided more information to universities about BIPs. Some of our universities are lobbying for such information to be provided by the end of April at the latest.

Similarly, in the case of the beginning and end of the virtual part of mobility - intuitively it will be just a pair of dates. But I'd rather not make assumptions on the basis of intuition - for example, when they will be mandatory, when they will be optional, and when they will not be allowed.

**Comment by janinamincer-daszkiewicz** [comment]
We will add to the API the field with information about the mobility, with possible values:
- Traineeship mobility
- Long term mobility for studies
- Blended mobility with short-term physical mobility
- Short-term doctoral mobility

Terminology is yet to be decided.
 
For the time being we postpone the decision on additional parameters, like start/end dates of virtual component. We need more feedback on how HEIs will handle these processes internally.

**Comment by janinamincer-daszkiewicz** [comment]
After long internal discussion (DG EAC experts involved) we have chosen the folowing change proposal:
We add two fields to nomination:

1. one for 'studies/traineeship',
2. the other for 'category' with values

- Long-term physical mobility
- Short term blended mobility with a compulsory virtual component
- Short term doctoral mobility with an optional virtual component

We *do not* add extra field for student/graduate as it is not important at the time of the nomination.
