### ISSUE TITLE
File ID and its contents

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-mobilities#44]
Can we rely on the file ID to change if the contents changes?

https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/nominations/endpoints/get-response.xsd#L563-L570

If so, it would mean that client implementers can reduce traffic when refreshing an existing nomination and retrieve only files that have changed. If not, they may have to invoke the File API unnecessarily.

Would it be possible to add the requirement to the specification that the file ID must change if the contents changes? The file ID could then be inferred from the checksum of the contents, for example.

**Comment by mkurzydlowski** [comment]
It's up to us to decide which way we want to go in regard to file changes. There are two possible solutions:

1. We require the server to not change the file being served. Every file change has to change to file id. The requester will need to rely on CNR to keep up with the changes.
2. The requester should ask for the file every time it needs it. The requester doesn't need to rely on CNR to be sure that he gets the latest version. Caching is used to reduce bandwidth.

It's worth mentioning that not relying on CNR makes this API self sufficient.

What other pros and cons do you find?

**Comment by mkurzydlowski** [comment]
There is one more argument for choosing one solution over another.

The requester might want to know a file has changed even if he wasn't attempting to use it at the moment. This use case is covered by solution 1, so I'm also leaning that way, even if this means relying on CNRs for file changes.

**Comment by jiripetrzelka** [comment]
I prefer the first option.

**Comment by kkaraogl** [comment]
Having CNRs for file changes seems like an overkill. The use case is that (probably) the student uploads these one-time in the context of the specific nomination, for this specific negotiation between institutions, and they have a meaning when the receiving party requests to view them. 

@jiripetrzelka will you allow for students in your application to change the submitted documents at any point in time?

**Comment by jiripetrzelka** [comment]
Although students are not allowed to change the documents themselves in our system (once they upload them), it can still be done by IRO coordinators, for example in case the student uploads a wrong document (which happens more often than one might expect). 

@kkaraogl I think that being prepared for all scenarios, including unlikely ones, is best. Otherwise we could start questioning whether all the other fields in the nomination are in fact immutable and if so, from which point in time. As far as I understand it, they are all mutable at any time except sending hei and receiving hei (which would result in a different mobility id, hence another nomination). It is my understanding that for example the planned-departure-date can change anytime during the mobility due to an extension having been approved, and the family name can change due to marriage, etc.

Maybe @mkurzydlowski could explain better the question of immutability.

**Comment by umesh-qs** [comment]
> Having CNRs for file changes seems like an overkill. The use case is that (probably) the student uploads these one-time in the context of the specific nomination, for this specific negotiation between institutions, and they have a meaning when the receiving party requests to view them.
> 
> @jiripetrzelka will you allow for students in your application to change the submitted documents at any point in time?

I don't think the proposed solution is asking for separate CNR. Mobility CNR should serve the purpose. Solution 1 looks good. Edit option should be given. It is up to the individual service provide to allow edit by the student or back office staff or both.

**Comment by umesh-qs** [comment]
Any particular reason why the max allowed document count is 1?

**Comment by jiripetrzelka** [comment]
I guess you can repeat the additional-requirement element as many times as you need and provide the same name sub-element multiple times.

Question is, why not allow for example this syntax:

```
<additional-requirement>
    <name>Portfolio</name>
    <file>85ba5392-fd35-4baa-9afa-220537d2ebbe</file>
    <url>https://www.youtube.com/watch?v=gdg34IFo</url>
</additional-requirement>

<additional-requirement>
    <name>Other document</name>
    <file>4a483112-d306-4e77-87ff-05b823fb0e0f</file>
    <file>f0f4934c-d384-41c3-a455-9bb9a689a5a3</file>
    <file>2f521e8a-d9fd-4f49-9941-df9318bf190f</file>
</additional-requirement>
```

But unless there is requirement that each name has to be unique, client implementers would still have to consider mutliple additional requirements with the same name to be possible, as it is now.

**Comment by umesh-qs** [comment]
What is the difference between file id and url. Why do we need both?

**Comment by jiripetrzelka** [comment]
We don't need both because there is a choice in https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/d703e55737fb936a7d0bb7cc099a36a4edc73dfa/endpoints/get-response.xsd#L562-L578

But the example here allows to provide both URL and file: https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/d703e55737fb936a7d0bb7cc099a36a4edc73dfa/endpoints/get-response-example.xml#L75-L82

So the choice can be circumvented by listing the same document multiple times.

**Comment by umesh-qs** [comment]
Do we really need url? If it is student related document, wouldn't it be private?

**Comment by jiripetrzelka** [comment]
Portfolio can be a video on YouTube. CV can be a link to Europass.

**Comment by umesh-qs** [comment]
Since a new File API is being proposed. Wouldn't it make sense to use "File Id" across all APIs that currently serve file content?

**Comment by jiripetrzelka** [comment]
I would like to point out that the question of immutability of certain fields, especially personal data, is currently not in line with the LA API, where these changes have to be approved by the counterparty. So if, for example, the surname changes, we currently can reflect it in this API immediately but in the LA API we cannot.

**Comment by mkurzydlowski** [comment]
@kkaraogl, am I right to assume that you prefer solution 2, mentioned in my first comment?

**Comment by kkaraogl** [comment]
> @kkaraogl, am I right to assume that you prefer solution 2, mentioned in my first comment?

Correct.

**Comment by umesh-qs** [comment]
> It's up to us to decide which way we want to go in regard to file changes. There are two possible solutions:
> 
> 1. We require the server to not change the file being served. Every file change has to change to file id. The requester will need to rely on CNR to keep up with the changes.
> 2. The requester should ask for the file every time it needs it. The requester doesn't need to rely on CNR to be sure that he gets the latest version. Caching is used to reduce bandwidth.
> 
> It's worth mentioning that not relying on CNR makes this API self sufficient.
> 
> What other pros and cons do you find?

For solution 2, what I understand is that partner will store a local copy and will only refresh the local copy when it is accessed in their system? But still how will the partner know that something has changed and needs their attention?

**Comment by mkurzydlowski** [comment]
If the client asks for the latest version of the file every time he needs to access the file, than maybe he doesn't need to be notified about file changes?

@kkaraogl, can you answer?

**Comment by umesh-qs** [comment]
@mkurzydlowski how will client know when to ask for latest version?

**Comment by kkaraogl** [comment]
As I've written above, the use case is that the student uploads these one-time in the context of the specific nomination, for this specific negotiation between institutions, and they have a meaning when the receiving party requests to view them (hence requesting the file, via this file api, client-side). 

Imagine the scenario of me applying for a job to Umesh and sharing my CV in pdf, as a url, from a remote server. Umesh will either hire me or turn me down. The file served its purpose in this negotiation. Why should I notify Umesh if my CV is changed?

Perhaps I am oversimplifying it, but this isn't about a general purpose file sharing system. It is simply exchanging some documents to accompany a student's nomination/application.

**Comment by umesh-qs** [comment]
@kkaraogl 
Before 'Umesh' makes a decision to hire or turn down, if you corrected the CV or any other document that might increase your chances of hiring, would you still be ok getting rejected? 

We should give some flexibility here. Not just assume that all docs are correctly uploaded.

**Comment by kkaraogl** [comment]
Yes, application procedures work this way. 

Requesting to view the file upon demand, client-side, when you need to make the decision, will actually be the latest version of the file. 

The scenario of an IRO that unilaterally changes a document submitted by the student, does not sit well with me. The scenario when at any stage a student can change their documents per specific nomination has some merit, I guess, but it seems to me that it should be handled on the application level (it is a student-sending matter, after all), before exchanging it with a remote partner.

**Comment by umesh-qs** [comment]
@kkaraogl 
Not sure what you mean by "handled on the application level". Please provide more details.
If there is a possibility of changes an existing document or adding a new document, then some way to notify the change has to be there. Else the partner will never know about it and will not open the application to see the changed documents.

**Comment by kkaraogl** [comment]
Allowing users to modify documents in the corresponding application (Dashboard, QS, etc.). Adding a new document will have a new file id whatever the case.

**Comment by umesh-qs** [comment]
@kkaraogl 
so you are saying that every time partner opens the mobility, get latest mobility and files data before displaying?

**Comment by umesh-qs** [comment]
Whether to call the file API on need basis is up to the implementer.
CNR is already there and can remain. Just need to extend to file changes.

**Comment by janinamincer-daszkiewicz** [comment]
My own subjective summary

1. I guess we can assume that a student is allowed to change the document locally many times, but at some moment he has to confirm that the document is ready.
2. The document with the other details of the nomination is shared with the partner (CNR followed by GET).
3. It may happen that some time later either the student or (most probable) the coordinator will change the file. However such situations should be rather rare.
This is similar to rare changes in other parts of the nomination.
We already have CNR to inform the partner of the changes in the nomination.
3. If so, let's agree that any change to the document made in (3) will *change the file id* and will *trigger CNR*, as any other change in nomination. Again, these should be really rare cases.
4. Then partners may catch files at the same moment they catch other details of nomination and can assume that all these elements are up to date until another CNR comes. After CNR and then GET they can compare the file id as they compare any other fields in nomination to conclude what has changed.

Alternatives:
3' and 4'. Change in file does not change file id, but CNR is sent. - The partner has to fetch file anyway, because does not know if the content remains the same, or can implement (2).
3'' and 4''. Change in file does not change file id, CNR is not sent. File has to be fetched before being shown to the user (subject to caching).

In that particular scenario when file changes are rare, I would vote for 3 and 4 above as simpler.
If the file owner decides to remove files after some time, we still can rely on our local copies if we need them.

**Comment by janinamincer-daszkiewicz** [comment]
1. We use file API to handle files in Omobilities API
 
https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/d703e55737fb936a7d0bb7cc099a36a4edc73dfa/endpoints/get-response.xsd#L563-L570 
<xs:element name="file" type="xs:string" minOccurs="1" maxOccurs="1">

2. There are two others APIs which handle files:
2.1. IIA:
https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/b8aed419061eba1b86c57389299841114bf500b1/endpoints/get-response.xsd#L248
<xs:element name="pdf" type="xs:base64Binary" minOccurs="0" maxOccurs="1">
2.2. IIA Approval:
https://github.com/erasmus-without-paper/ewp-specs-api-iias-approval/blob/20bf06e279f8acd2086c95bfd0af25316858a42b/response.xsd#L71
<xs:element name="pdf" type="xs:base64Binary" minOccurs="0" maxOccurs="1">

Do we want to change them to use the new file API? That would mean extra work for developers.

P.S. Files are also exchange in ToRs but this part of specification comes from ELMO.

**Comment by umesh-qs** [comment]
We believe that approach should be consistent for all the APIs having any kind of file use. This can be done along with next set of IIA changes. Yes there would a bit of work for calling the file API after calling the IIA API, but that logic can be reused from file changes in mobility API.

**Comment by mkurzydlowski** [comment]
I believe that we still need to decide on the solution. Let me get back to the main argument for using solution 1 over 2, that I see: 

> The requester might want to know a file has changed even if he wasn't attempting to use it at the moment. This use case is covered by solution 1.

@kkaraogl has pointed out that he doesn't see this functionality in the use cases.

If knowing about every file change is not needed then solution 2 seems a better fit, as it is simpler. It still gives the possibility to inform about a major file change by changing file id, at the will of the file owner.

But maybe we want to impose notifying about every file change by requiring the file owner to change file id? The business perspective is crucial here.

**Comment by umesh-qs** [comment]
Solution 2 can be implemented by individual providers irrespective of Solution 1.
We prefer CNR (Solution 1) for any change in the IIA. On receiving the CNR we will then refresh all the data irrespective of whether file id has changed or not.

**Comment by janinamincer-daszkiewicz** [comment]
During the Infrastructure meeting on 2022-04-06 the following options have been discussed and voted:

1. We require the server to not change the file being served. Every file change has to change to file id. The requester will need to rely on CNR to keep up with the changes.
	 
Change has been approved. This option will be implemented.

2. The requester should ask for the file every time it needs it. The requester doesn't need to rely on CNR to be sure that he gets the latest version. Caching is used to reduce bandwidth.

This option has been rejected.

3. Changes in two other APIs which handle files have been postponed, they will be made during future round of changes.

**Comment by janinamincer-daszkiewicz** [comment]
Some changes in the IIA and IIA Approval APIs will take place by the end of 2022. It makes sense to group them to make the change in the major number of the APIs once.

During the Infrastructure Forum meeting on 2022-11-16 the providers will vote if we want to introduce the option 3 from https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/issues/44#issuecomment-1113997116.

**Comment by janinamincer-daszkiewicz** [comment]
Voting took place during the Infrastructure Forum meeting on 2022-11-16. According to chat:
14 providers voted YES, one voted NO.

This change will be implemented under the condition that the others, more important ones, will be implemented.

**Comment by janinamincer-daszkiewicz** [comment]
Approved for IIA 7.0.0 release.
