### ISSUE TITLE
Correction proposal summary

### ISSUE THREAD

**Issue by serkanUH** [erasmus-without-paper/ewp-specs-api-mobilities#50]
Correction proposal summary : This document describes the Outgoing Mobilities API. This API is implemented by the sending institution. It allows the receiving HEI to read, **write** and enumerate mobilities stored on the sending HEI's servers.

I don't think receiving HEI can write on the sending HEI's server. Please clearify "write" or explain in summary if meant differently.

**Comment by kamil-olszewski-uw** [comment]
You're right. This must be a thing of the past when receiving HEI was able to alter some data with this API. This is now done using the Incoming Mobilities API. We'll fix this.
