### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by serkanUH** [erasmus-without-paper/ewp-specs-api-mobilities#51]
On the global-id section of student the [https://github.com/erasmus-without-paper/european-student-identifier](https://github.com/erasmus-without-paper/european-student-identifier) ( line 321 ) link is dead. Rip

**Comment by kamil-olszewski-uw** [comment]
You're right. We'll change it to https://wiki.geant.org/display/SM/European+Student+Identifier
