### ISSUE TITLE
Planned dates and extensions

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-mobilities#52]
If the mobility is extended, for example if the student decides (and gets approval) to prolong the stay from one semester to entire year, should the planned departure date be updated by the sending institution?

https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/9e48843951c760af4bf1958e0f94dda7b381b588/endpoints/get-response.xsd#L489-L496

Or should this always reflect the original dates that have been signed in the Participant's Agreement?

**Comment by kamil-olszewski-uw** [comment]
This is a business question rather than a technical one. You should probably change the date, but I guess there are no strict European Commission guidelines on this. Maybe you should ask your National Agency.

**Comment by jiripetrzelka** [comment]
If I am to ask NA about it, I will need to point them to the underlying document based on which the specification has been created. Can you point me to the template or website which you based the specification on?

**Comment by kamil-olszewski-uw** [comment]
https://erasmus-plus.ec.europa.eu/resources-and-tools/mobility-and-learning-agreements/learning-agreement

I have now searched the guidelines on this page again, but I think there is nothing to answer your question.

**Comment by lioliosn** [comment]
If we take the OLA implementation as a reference implementation (since it is based on the LA template), then planned dates should change in case of an extension. There is no specific rule, but it is common (IRO) sense.

**Comment by jiripetrzelka** [comment]
I agree with @lioliosn that if the API is based on the LA template then we should provide the most up-to-date dates and I think that this should be clearly stated in the documentation so that each partner can be sure what dates they get from the counterparty.
