### ISSUE TITLE
Element agreement-isced-f-code

### ISSUE THREAD

**Issue by spinho-uporto** [erasmus-without-paper/ewp-specs-api-mobilities#58]
The agreement-isced-f-code element in the Outgoing Mobilities API v3 states: "The sending HEI indicates the ISCED field of education of the agreement's cooperation condition they want to nominate the student on."

Are there any recommendations for handling agreements approved in v6 that use ISCED codes differing from 4-digit codes?

**Comment by kamil-olszewski-uw** [comment]
In such cases it will be good to use a four-digit code that will best match the non-four-digit code from the cooperation conditions. This will not provide a technical link between the IIA and the nomination, but at least a functional one.

**Comment by spinho-uporto** [comment]
Thank you for the clarification.
