### ISSUE TITLE
Single IIA for Mobility?

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-api-mobilities#6]
get-response-example.xml has different iia-id's for the sending and receiving HEIs.
I assume the two HEIs need to agree :-) on which IIA the Mobility is subject too, and therefore iia-id should be a single element parallel to sending-hei and receiving-hei?

**Comment by kaiqu** [comment]
> get-response-example.xml has different iia-id's for the sending and receiving HEIs.
> I assume the two HEIs need to agree :-) on which IIA the Mobility is subject too, and therefore iia-id should be a single element parallel to sending-hei and receiving-hei?

The XSD annotation says the two iia-id's are optional and local to each HEI. The model allows for local IIA ID's, but mustn't there be a global ID they agree on, to make sure they are talking about the same IIA, @wrygiel ?

**Comment by kaiqu** [comment]
> mustn't there be a global ID they agree on, to make sure they are talking about the same IIA

After reading the IIAs description (which I should have done to begin with), I understand. But I think the model may need to be changed here, as it describes a _global_ IIA concept...

**Comment by wrygiel** [comment]
> I assume the two HEIs need to agree :-) on which IIA the Mobility is subject too, and therefore iia-id should be a single element parallel to sending-hei and receiving-hei?

Initially, I thought the same. But this would require all partners to agree on a single UUID before they can serve an IIA. And this sounds like trouble.
