### ISSUE TITLE
Mobility status

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-api-mobilities#7]
In the model, suggested statuses are Nominated, Accepted and Rejected.
But the get-response example has status = "live"?

**Comment by kaiqu** [comment]
> In the model, suggested statuses are Nominated, Accepted and Rejected.
> But the get-response example has status = "live"?

I see the XSD has "nomination", "live", "rejected", "recognized" and "cancelled". The last two are new and presumably necessary (I will update the model). The first three correspond to Nominated, Accepted and Rejected in the model. I think standardizing on "verb in past tense" is more consistent, but I don't have strong opinions about it. However, the model and XSD should be consistent with each other, so let me know what you decide.

**Comment by wrygiel** [comment]
The difference comes from the fact, that the model dealt with "the status of the nomination", and I have tried to expand this to a bit broader "status of the mobility".

However, I'm not sure if my initial proposal is the best approach (we could have trouble when it comes to adding more statuses in the future). Other solutions are possible. For example this could work too:

```xml
<nomination-status>accepted</nomination-status>
<recognized>true</recognized>
<cancelled>false</cancelled>
```

What do you think? Which solution seems better to you?

@erasmus-without-paper/all-members

**Comment by kaiqu** [comment]
> However, I'm not sure if my initial proposal is the best approach (we could have trouble when it comes to adding more statuses in the future). Other solutions are possible. For example this could work too:
>
> "nomination-status" = accepted
> "recognized" = true
> "cancelled" = false
>
> What do you think? Which solution seems better to you?

(I have replaced the field brackets with double quotes to keep quoted text readable)

There are two concerns here:
- Orthogonal (independent) value sets should be represented by different fields, while mutually exclusive value sets should be represented by the same field
- All values should be intuitively understandable in the context of the field name

The above code examples would therefore make sense if:
- "nomination-status" e.g. has the value set nominated/accepted/rejected
- "recognized" and "cancelled" are orthogonal to each other and to "nomination-status" - i.e. (possibly a subset of) all combinations are possible

What would be the possible combinations of these three fields?

**Comment by wrygiel** [comment]
> What would be the possible combinations of these three fields?

I believe that only accepted nominations can be recognized (1 combination here). But also not-yet-accepted nominations can be cancelled (2 combinations).

**Comment by kaiqu** [comment]
> I believe that only accepted nominations can be recognized (1 combination here).

But they don't _have_ to be, so there are two combinations.

> But also not-yet-accepted nominations can be cancelled (2 combinations).

So we have the following states:
- nominated
- nominated + cancelled
- rejected
- accepted
- accepted + recognized

Which translates to the following combinations of the three suggested fields:

nomination-status | cancelled | recognized
:-------------------: | :---------: | :-----------:
nominated             | false        | N/A
nominated             | true         | N/A
rejected                  | N/A         | N/A
accepted                | N/A         | false
accepted                | N/A         | true

This leaves most combinations unused, and I would rather suggest a single Status field with these values and transitions:
- nominated => cancelled / accepted / rejected
- accepted => recognized

**Comment by kaiqu** [comment]
> Anyway, I believe "accepted => cancelled" is also a perfectly valid transition. Also "cancelled => nominated" might be possible, or even "cancelled => accepted".

Ok. Then there are so many valid transitions that it doesn't seem to be much point in defining validity.

> Do you think that "accepted mobility" is better than "live mobility"?

On second thought, I guess "live" is somewhat better. Which leaves us with the following statuses:
- nominated
- live
- rejected
- cancelled
- recognized

**Comment by wrygiel** [comment]
>> Do you think that "accepted mobility" is better than "live mobility"?

BTW - I have used "nomination" instead of "nominated" for similar reasons (because "nomination-mobility" sounded a just slightly better than "nominated mobility").

I'm still not certain whether these 5 statuses will be enough, but I think we still have a couple of months before we upgrade this specs to "stable".
